name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build Jekyll site
        run: bundle exec jekyll build
      - name: Install mdbook
        run: |
          MDBOOK_VERSION="$(grep '^mdbook = ' mise.toml | sed -E 's/.*"(.+)".*/\1/')"
          curl -sSL "https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz" | tar -xz
          sudo mv mdbook /usr/local/bin/
      - name: Build mdbook (pizero)
        working-directory: pizero
        run: mdbook build
      - name: Build mdbook (electronics)
        working-directory: electronics
        run: mdbook build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy _site --project-name=chirimen-org
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
